# Generated by Django 3.1.7 on 2021-04-20 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='زمان بروز رسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('title', models.CharField(max_length=32, verbose_name='عنوان')),
                ('related_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priority_creator_related', related_query_name='priority_creator', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name': 'اولویت',
                'verbose_name_plural': 'اولویت ها',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='زمان بروز رسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('subject', models.CharField(max_length=32, verbose_name='موضوع')),
                ('email', models.CharField(max_length=128, verbose_name='آدرس ایمیل')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت ها',
            },
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='زمان بروز رسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('title', models.CharField(max_length=128, verbose_name='عنوان')),
                ('related_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticketcategory_creator_related', related_query_name='ticketcategory_creator', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name': 'دسته بندی تیکت',
                'verbose_name_plural': 'دسته بندی های تیکت',
            },
        ),
        migrations.CreateModel(
            name='UserReferRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='زمان بروز رسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('related_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userreferrequest_creator_related', related_query_name='userreferrequest_creator', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('related_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.ticket', verbose_name='تیکت مربوطه')),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_refer_request_related_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مربوطه')),
            ],
            options={
                'verbose_name': 'درخواست ارجاع به کاربر',
                'verbose_name_plural': 'درخواست های ارجاع به کاربر',
            },
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='زمان بروز رسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('title', models.CharField(max_length=32, verbose_name='عنوان')),
                ('related_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticketstatus_creator_related', related_query_name='ticketstatus_creator', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name': 'وضعیت تیکت',
                'verbose_name_plural': 'وضعیت های تیکت',
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='زمان بروز رسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن')),
                ('related_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticketmessage_creator_related', related_query_name='ticketmessage_creator', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('related_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.ticket', verbose_name='تیکت مربوطه')),
            ],
            options={
                'verbose_name': 'پیام تیکت',
                'verbose_name_plural': 'پیام های تیکت',
            },
        ),
        migrations.CreateModel(
            name='TicketFileAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='زمان بروز رسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('file', models.FileField(upload_to='', verbose_name='فایل پیوست')),
                ('related_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticketfileattachment_creator_related', related_query_name='ticketfileattachment_creator', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('related_ticket_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.ticketmessage', verbose_name='پیام مربوطه')),
            ],
            options={
                'verbose_name': 'فایل پیوست تیکت',
                'verbose_name_plural': 'فایل های پیوست تیکت',
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='زمان بروز رسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('text', models.TextField(verbose_name='متن')),
                ('related_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticketcomment_creator_related', related_query_name='ticketcomment_creator', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('related_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.ticket', verbose_name='تیکت مربوطه')),
            ],
            options={
                'verbose_name': 'کامنت تیکت',
                'verbose_name_plural': 'کامنت های تیکت',
            },
        ),
        migrations.CreateModel(
            name='TicketCategoryUserAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='زمان بروز رسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('related_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticketcategoryuserassignment_creator_related', related_query_name='ticketcategoryuserassignment_creator', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('related_ticket_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.ticketcategory', verbose_name='دسته بندی تیکت مربوطه')),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_category_user_assignment_related_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مربوطه')),
            ],
            options={
                'verbose_name': 'کارشناس مدیریت تیکت',
                'verbose_name_plural': 'کارشناس های مدیریت تیکت',
            },
        ),
        migrations.CreateModel(
            name='TicketCategoryReferRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='زمان بروز رسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('related_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticketcategoryreferrequest_creator_related', related_query_name='ticketcategoryreferrequest_creator', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('related_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.ticket', verbose_name='تیکت مربوطه')),
                ('related_ticket_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketing.ticketcategory', verbose_name='دسته بندی مربوطه')),
            ],
            options={
                'verbose_name': 'درخواست ارجاع به بخش تیکتینگ',
                'verbose_name_plural': 'درخواست های ارجاع به بخش تیکتینگ',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='referred_to_ticket_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_referred_to_ticket_category', to='ticketing.ticketcategory', verbose_name='ارجاع شده به بخش تیکتینگ'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='referred_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_referred_to_user', to=settings.AUTH_USER_MODEL, verbose_name='ارجاع شده به کاربر'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='related_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_creator_related', related_query_name='ticket_creator', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='related_priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketing.priority', verbose_name='اولویت'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='related_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.subscription', verbose_name='اشتراک مربوطه'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='related_ticket_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketing.ticketcategory', verbose_name='بخش مربوطه'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='related_ticket_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketing.ticketstatus', verbose_name='وضعیت تیکت مربوطه'),
        ),
        migrations.AddIndex(
            model_name='userreferrequest',
            index=models.Index(fields=['related_ticket'], name='ticketing_u_related_5cb0c3_idx'),
        ),
        migrations.AddIndex(
            model_name='userreferrequest',
            index=models.Index(fields=['related_user'], name='ticketing_u_related_3f281b_idx'),
        ),
        migrations.AddIndex(
            model_name='userreferrequest',
            index=models.Index(fields=['related_ticket', 'related_user'], name='ticketing_u_related_e1762d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketstatus',
            index=models.Index(fields=['title'], name='ticketing_t_title_8f38b4_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['related_ticket'], name='ticketing_t_related_dab5b4_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketfileattachment',
            index=models.Index(fields=['related_ticket_message'], name='ticketing_t_related_5bf554_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcomment',
            index=models.Index(fields=['related_ticket'], name='ticketing_t_related_56a478_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcategoryuserassignment',
            index=models.Index(fields=['related_ticket_category'], name='ticketing_t_related_ada4f7_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcategoryuserassignment',
            index=models.Index(fields=['related_user'], name='ticketing_t_related_dffffe_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcategoryuserassignment',
            index=models.Index(fields=['related_ticket_category', 'related_user'], name='ticketing_t_related_109dee_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcategoryreferrequest',
            index=models.Index(fields=['related_ticket'], name='ticketing_t_related_780ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcategoryreferrequest',
            index=models.Index(fields=['related_ticket_category'], name='ticketing_t_related_beb3e4_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcategoryreferrequest',
            index=models.Index(fields=['related_ticket', 'related_ticket_category'], name='ticketing_t_related_0a950e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcategory',
            index=models.Index(fields=['title'], name='ticketing_t_title_ea7b9f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['related_priority'], name='ticketing_t_related_c6c1ca_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['related_ticket_category'], name='ticketing_t_related_e3c8d7_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['related_subscription'], name='ticketing_t_related_dc36aa_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['email'], name='ticketing_t_email_05195a_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['referred_to_ticket_category'], name='ticketing_t_referre_8d3548_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['referred_to_user'], name='ticketing_t_referre_642439_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['related_priority', 'related_ticket_category'], name='ticketing_t_related_12ad11_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['related_priority', 'related_subscription'], name='ticketing_t_related_01c113_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['related_ticket_category', 'related_subscription'], name='ticketing_t_related_42aa6f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['related_priority', 'related_ticket_category', 'related_subscription'], name='ticketing_t_related_dd4eed_idx'),
        ),
        migrations.AddIndex(
            model_name='priority',
            index=models.Index(fields=['title'], name='ticketing_p_title_ac2640_idx'),
        ),
    ]
