# Generated by Django 3.1.7 on 2021-03-08 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan', '0002_auto_20210308_1139'),
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
        migrations.AlterField(
            model_name='priority',
            name='title',
            field=models.CharField(max_length=32, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='email',
            field=models.CharField(max_length=128, verbose_name='آدرس ایمیل'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='related_priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketing.priority', verbose_name='اولویت'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='related_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.subscription', verbose_name='اشتراک مربوطه'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='related_ticket_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketing.ticketcategory', verbose_name='بخش مربوطه'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(max_length=32, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='title',
            field=models.CharField(max_length=128, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='ticketfileattachment',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
        migrations.AlterField(
            model_name='ticketfileattachment',
            name='file',
            field=models.FileField(upload_to='', verbose_name='فایل پیوست'),
        ),
        migrations.AlterField(
            model_name='ticketfileattachment',
            name='related_ticket_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.ticketmessage', verbose_name='پیام مربوطه'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='related_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.ticket', verbose_name='تیکت مربوطه'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='متن'),
        ),
    ]
