# Generated by Django 3.1.7 on 2021-03-09 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_auto_20210309_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='related_ticket_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketing.ticketstatus', verbose_name='وضعیت تیکت مربوطه'),
        ),
    ]
