# Generated by Django 3.1.7 on 2021-03-09 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketing', '0004_ticket_related_ticket_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='زمان بروز رسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('text', models.TextField()),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('related_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.ticket', verbose_name='تیکت مربوطه')),
            ],
        ),
        migrations.AddIndex(
            model_name='ticketcomment',
            index=models.Index(fields=['related_ticket'], name='ticketing_t_related_56a478_idx'),
        ),
    ]
