# Generated by Django 3.1.7 on 2021-03-10 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketing', '0005_auto_20210309_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcomment',
            name='text',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.CreateModel(
            name='TicketCategoryUserAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='زمان بروز رسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('related_ticket_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.ticketcategory', verbose_name='دسته بندی تیکت مربوطه')),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_category_user_assignment_related_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مربوطه')),
            ],
        ),
        migrations.AddIndex(
            model_name='ticketcategoryuserassignment',
            index=models.Index(fields=['related_ticket_category'], name='ticketing_t_related_ada4f7_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcategoryuserassignment',
            index=models.Index(fields=['related_user'], name='ticketing_t_related_dffffe_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcategoryuserassignment',
            index=models.Index(fields=['related_ticket_category', 'related_user'], name='ticketing_t_related_109dee_idx'),
        ),
    ]
