# Generated by Django 3.1.7 on 2021-03-14 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketing', '0006_auto_20210310_0547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name': 'اولویت', 'verbose_name_plural': 'اولویت ها'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت ها'},
        ),
        migrations.AlterModelOptions(
            name='ticketcategory',
            options={'verbose_name': 'دسته بندی تیکت', 'verbose_name_plural': 'دسته بندی های تیکت'},
        ),
        migrations.AlterModelOptions(
            name='ticketcategoryuserassignment',
            options={'verbose_name': 'کارشناس مدیریت تیکت', 'verbose_name_plural': 'کارشناس های مدیریت تیکت'},
        ),
        migrations.AlterModelOptions(
            name='ticketcomment',
            options={'verbose_name': 'کامنت تیکت', 'verbose_name_plural': 'کامنت های تیکت'},
        ),
        migrations.AlterModelOptions(
            name='ticketfileattachment',
            options={'verbose_name': 'فایل پیوست تیکت', 'verbose_name_plural': 'فایل های پیوست تیکت'},
        ),
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'verbose_name': 'پیام تیکت', 'verbose_name_plural': 'پیام های تیکت'},
        ),
        migrations.AlterModelOptions(
            name='ticketstatus',
            options={'verbose_name': 'وضعیت تیکت', 'verbose_name_plural': 'وضعیت های تیکت'},
        ),
        migrations.CreateModel(
            name='TicketCategoryReferRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='زمان بروز رسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('related_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.ticket', verbose_name='تیکت مربوطه')),
                ('related_ticket_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketing.ticketcategory', verbose_name='دسته بندی مربوطه')),
            ],
            options={
                'verbose_name': 'درخواست ارجاع به بخش تیکتینگ',
                'verbose_name_plural': 'درخواست های ارجاع به بخش تیکتینگ',
            },
        ),
        migrations.AddIndex(
            model_name='ticketcategoryreferrequest',
            index=models.Index(fields=['related_ticket'], name='ticketing_t_related_780ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcategoryreferrequest',
            index=models.Index(fields=['related_ticket_category'], name='ticketing_t_related_beb3e4_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcategoryreferrequest',
            index=models.Index(fields=['related_ticket', 'related_ticket_category'], name='ticketing_t_related_0a950e_idx'),
        ),
    ]
