# Generated by Django 3.1.7 on 2021-03-14 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketing', '0007_auto_20210314_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='referred_to_ticket_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_referred_to_ticket_category', to='ticketing.ticketcategory', verbose_name='ارجاع شده به بخش تیکتینگ'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='referred_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_referred_to_user', to=settings.AUTH_USER_MODEL, verbose_name='ارجاع شده به کاربر'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['referred_to_ticket_category'], name='ticketing_t_referre_8d3548_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['referred_to_user'], name='ticketing_t_referre_642439_idx'),
        ),
    ]
