# Generated by Django 3.1.7 on 2021-03-14 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketing', '0008_auto_20210314_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReferRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='زمان بروز رسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('related_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.ticket', verbose_name='تیکت مربوطه')),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_refer_request_related_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مربوطه')),
            ],
            options={
                'verbose_name': 'درخواست ارجاع به کاربر',
                'verbose_name_plural': 'درخواست های ارجاع به کاربر',
            },
        ),
        migrations.AddIndex(
            model_name='userreferrequest',
            index=models.Index(fields=['related_ticket'], name='ticketing_u_related_5cb0c3_idx'),
        ),
        migrations.AddIndex(
            model_name='userreferrequest',
            index=models.Index(fields=['related_user'], name='ticketing_u_related_3f281b_idx'),
        ),
        migrations.AddIndex(
            model_name='userreferrequest',
            index=models.Index(fields=['related_ticket', 'related_user'], name='ticketing_u_related_e1762d_idx'),
        ),
    ]
