# Generated by Django 3.1.7 on 2021-03-09 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan', '0002_auto_20210308_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionServiceAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='زمان بروز رسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('related_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.service')),
                ('related_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.subscription')),
            ],
        ),
        migrations.AddIndex(
            model_name='subscriptionserviceassignment',
            index=models.Index(fields=['related_subscription'], name='plan_subscr_related_47ea07_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionserviceassignment',
            index=models.Index(fields=['related_service'], name='plan_subscr_related_1534e9_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionserviceassignment',
            index=models.Index(fields=['related_subscription', 'related_service'], name='plan_subscr_related_c2f96f_idx'),
        ),
    ]
