# Generated by Django 3.1.7 on 2021-03-13 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan', '0005_auto_20210313_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionServiceAssignmentField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='زمان بروز رسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('related_service_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.servicefield')),
                ('related_subscription_service_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.subscriptionserviceassignment')),
            ],
        ),
        migrations.AddIndex(
            model_name='subscriptionserviceassignmentfield',
            index=models.Index(fields=['related_subscription_service_assignment'], name='plan_subscr_related_c92ee9_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionserviceassignmentfield',
            index=models.Index(fields=['related_service_field'], name='plan_subscr_related_c166e8_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionserviceassignmentfield',
            index=models.Index(fields=['related_subscription_service_assignment', 'related_service_field'], name='plan_subscr_related_059595_idx'),
        ),
    ]
