# Generated by Django 3.1.7 on 2021-03-14 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_auto_20210313_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'سرویس', 'verbose_name_plural': 'سرویس ها'},
        ),
        migrations.AlterModelOptions(
            name='servicefield',
            options={'verbose_name': 'فیلد سرویس', 'verbose_name_plural': 'فیلدهای سرویس'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'اشتراک', 'verbose_name_plural': 'اشتراک ها'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionserviceassignment',
            options={'verbose_name': 'سرویس در اشتراک', 'verbose_name_plural': 'سرویس های اشتراک'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionserviceassignmentfield',
            options={'verbose_name': 'فیلد متصل شده به سرویس اشتراک', 'verbose_name_plural': 'فیلد های متصل شده به سرویس اشتراک'},
        ),
    ]
